Make font weights more aligned with XCode
CodeEditApp/CodeEditSourceEditor pull request #245
Opened 2024-05-02 17:16 UTC by danielzsh

### Description
This PR makes CodeEdit's font weights align more with XCode's.

Before:
<img width="517" alt="image" src="https://github.com/CodeEditApp/CodeEditSourceEditor/assets/65467530/e88061c7-f994-4195-81e3-5013b202abd3">

After:
<img width="563" alt="image" src="https://github.com/CodeEditApp/CodeEditSourceEditor/assets/65467530/e2337274-d1ad-4a78-9fe6-d578cbe60e7c">

XCode:
<img width="392" alt="image" src="https://github.com/CodeEditApp/CodeEditSourceEditor/assets/65467530/9ef70418-ee0f-48de-b0f0-5f395079f8f3">

This PR notably lacks support for specifying customs weights in the theme file, and instead hardcodes weights based on symbol for the time being; I'm open to either working on supporting theme file now or after this PR is merged :)

### Related Issues

* Closes https://github.com/CodeEditApp/CodeEdit/issues/1686

### Checklist

- [x] I read and understood the [contributing guide](https://github.com/CodeEditApp/CodeEdit/blob/main/CONTRIBUTING.md) as well as the [code of conduct](https://github.com/CodeEditApp/CodeEdit/blob/main/CODE_OF_CONDUCT.md)
- [x] The issues this PR addresses are related to each other
- [x] My changes generate no new warnings
- [x] My code builds and runs on my machine
- [x] My changes are all related to the related issue above
- [x] I documented my code

### Screenshots

2024-05-03 00:45 UTC, FastestMolasses submitted a review, later dismissed

2024-05-03 01:01 UTC, austincondiff requested changes
Correct me if I’m wrong, but are you putting a stroke around each character to get a thicker weight? Xcode uses a medium weight. CodeEdit currently uses a normal weight. I think changing our default weight to medium is what probably needs to happen instead.

2024-05-03 01:24 UTC, danielzsh commented
I believe the default weight is already medium, as seen here: https://github.com/CodeEditApp/CodeEdit/blob/0f87857497d24f65b6310634251f63d8e3935c3d/CodeEdit/Features/Settings/Pages/TextEditingSettings/Models/TextEditingSettings.swift#L185

But XCode goes even further as to highlight keywords and certain other tokens with bold (notice in the XCode screenshot the variable names have the same weight as CodeEdit's current font).

2024-05-03 15:32 UTC, danielzsh commented
Actually, -5.0 might be closer:
<img width="1198" alt="image" src="https://github.com/CodeEditApp/CodeEditSourceEditor/assets/65467530/bff4a2e8-3482-4a20-af79-7841030a8026">

2024-05-11 06:13 UTC, danielzsh commented
@austincondiff bump?

2024-05-11 20:33 UTC, austincondiff commented
I don’t think this is the correct way to change the font weight. @thecoolwinter do you have any ideas how we might better do this?

2024-05-13 03:34 UTC, thecoolwinter commented
Instead of increasing weight via stroke width, using font weights directly would be more robust for various fonts. Different fonts use different stroke widths for each weight, so using a constant stroke width modifier for certain captures might result in slightly different typeface than expected.

I hate to ask you to throw away this work, but I'd also rather it be tied to the theme rather than hardcoded to specific captures. That'll be more flexible for users, and fits in with existing theme code. It should just require a change to the theme struct and `ThemeAttributesProviding` protocol

2024-05-16 15:17 UTC, closed without merging